Repository brainelectronics/micropython-modbus, pull requests merged in 2022-12, with the labels that each got.

#32 Update README.md
  README.md
Labels: documentation

#33 Create test framework
  .flake8
  .github/workflows/test.yml
  .gitignore
  .gitmodules
  .readthedocs.yaml
  Dockerfile.client
  Dockerfile.host
  Dockerfile.test_tcp_example
  Dockerfile.tests
  README.md
  USAGE.md
  changelog.md
  docker-compose-tcp-test.yaml
  docker-compose.yaml
  docs/CONTRIBUTING.md
  docs/SETUP.md
  docs/UPGRADE.md
  docs/USAGE.md
  docs/changelog_link.rst
  docs/conf.py
  docs/index.rst
  docs/readme_link.rst
  docs/requirements.txt
  docs/umodbus.rst
  examples/example.json
  examples/read_registers_rtu.sh
  examples/read_registers_tcp.sh
  examples/rtu_client_example.py
  examples/tcp_client_example.py
  examples/tcp_host_example.py
  examples/write_registers_tcp.sh
  mpy_unittest.py
  registers/example.json
  registers/set-example.json
  setup.py
  tests/__init__.py
  tests/test_absolute_truth.py
  tests/test_const.py
  tests/test_functions.py
  tests/test_tcp_example.py
  umodbus/const.py
  umodbus/functions.py
  umodbus/modbus.py
  umodbus/serial.py
  umodbus/tcp.py
  umodbus/typing.py
Labels: bug, documentation, enhancement, CICD

#39 Add all missing docstrings and typing hints, improve docs, fix some but not all bugs
  README.md
  changelog.md
  docs/USAGE.md
  docs/umodbus.rst
  registers/example.json
  tests/test_functions.py
  tests/test_tcp_example.py
  umodbus/common.py
  umodbus/const.py
  umodbus/functions.py
  umodbus/modbus.py
  umodbus/serial.py
  umodbus/tcp.py
Labels: bug, documentation

#41 Restore Client support for Modbus RTU
  Dockerfile.client
  Dockerfile.host
  Dockerfile.test_tcp_example
  Dockerfile.tests
  changelog.md
  docs/SETUP.md
  setup.py
  umodbus/modbus.py
  umodbus/tcp.py
Labels: bug

#42 Use most generic UART functions
  changelog.md
  umodbus/serial.py
Labels: bug

#45 Remove hardcoded UART ID from Modbus RTU
  changelog.md
  docs/USAGE.md
  examples/rtu_client_example.py
  umodbus/serial.py
Labels: bug, documentation
