Repository brainelectronics/micropython-modbus, pull requests merged in 2023-07, with the labels that each got.

#75 Fix timing issues with UART communication
  changelog.md
  fakes/machine.py
  umodbus/serial.py
Labels: bug, enhancement

#78 Add contribution guideline
  .github/workflows/test.yml
  .gitmodules
  .pre-commit-config.yaml
  Dockerfile.client_rtu
  Dockerfile.client_tcp
  Dockerfile.host_rtu
  Dockerfile.host_tcp
  Dockerfile.test_examples
  Dockerfile.tests
  Dockerfile.tests_manually
  changelog.md
  docker-compose-rtu-test.yaml
  docker-compose-rtu.yaml
  docker-compose-tcp-test.yaml
  docs/CONTRIBUTING.md
  docs/changelog_link.rst
  docs/readme_link.rst
  package.json
  requirements-deploy.txt
  requirements-test.txt
  requirements.txt
  tests/ulogging.py
  umodbus/version.py
Labels: documentation

#79 Add single char wait time after flush to avoid RTU control pin timing issue
  changelog.md
  package.json
  umodbus/serial.py
  umodbus/version.py
Labels: bug
